/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Attribute: typeof import('./components/Attribute.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    Recursive: typeof import('./components/Recursive.vue')['default']
    Root: typeof import('./components/Root.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SubHtml: typeof import('./components/SubHtml.vue')['default']
    Success: typeof import('./components/Success.vue')['default']
  }
}
