name: PR Build Test
on:
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v31
      with:
        extra_nix_config: |
          trusted-public-keys = hydra.iohk.io:f/Ea+s+dFdN+3Y/G+FDgSq+a5NEWhJGzdjvKNGv0/EQ= cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY=
          substituters = https://cache.iog.io/ https://cache.nixos.org/
          allow-import-from-derivation = true
          accept-flake-config = true
          download-buffer-size = 524288000
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: cachix/cachix-action@v15
      with:
        name: inguncache
        # authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
    - name: Checkout DB
      uses: actions/checkout@v5
      with:
        repository: 'ingun37/answers-db'
        path: 'answers-db'
        fetch-depth: 0

    - run: |
        nix run --no-write-lock-file "github:ingun37/answers-script#answers-script:exe:answers-script" -- --src answers-db --dst public --prefix answers
    - uses: pnpm/action-setup@v4
      name: Install pnpm
      with:
        version: 10
        run_install: false
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 22.x
        cache: 'pnpm'

    - name: Install dependencies
      run: pnpm install
    - run: pnpm build